# Generated by Django 4.2.7 on 2024-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imeage',
            field=models.ImageField(blank=True, null=True, upload_to='BlogImeage/'),
        ),
    ]
