# Generated by Django 4.2.7 on 2024-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hour', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
