# Generated by Django 4.2.7 on 2024-01-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePhoto/'),
        ),
        migrations.AddField(
            model_name='user',
            name='ratting',
            field=models.FloatField(default=0),
        ),
    ]
